openapi: 3.0.3
info:
  title: Smart Contract Search API
  description: API for searching smart contracts using semantic search
  version: 2.0.0
  contact:
    name: API Support
  license:
    name: MIT

servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /search:
    post:
      summary: Search smart contracts
      description: Search for smart contracts using semantic search with optional detailed contract data
      operationId: searchContracts
      tags:
        - contracts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequest"
            examples:
              basic_search:
                summary: Basic search without detailed data
                value:
                  query: "ERC20 token"
                  limit: 10
                  data: false
              detailed_search:
                summary: Search with detailed contract data
                value:
                  query: "DeFi lending protocol"
                  limit: 5
                  data: true
      responses:
        "200":
          description: Successful search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ContractResult"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    SearchRequest:
      type: object
      required:
        - query
        - limit
      properties:
        query:
          type: string
          description: Search query string to find relevant contracts
          example: "ERC20 token contract"
          minLength: 1
        limit:
          type: integer
          description: Maximum number of results to return
          example: 10
          minimum: 1
          maximum: 100
        data:
          type: boolean
          description: Whether to include detailed contract data
          default: false
          example: true

    ContractResult:
      type: object
      required:
        - id
        - name
        - description
        - created
        - verified
        - tags
      properties:
        id:
          type: string
          description: Unique identifier for the contract
          example: "0x123abc"
        name:
          type: string
          description: Name of the smart contract
          example: "MyToken"
        symbol:
          type: string
          description: Symbol of the token (if applicable)
          example: "MTK"
          default: ""
        description:
          type: string
          description: Description of the contract
          example: "A comprehensive ERC20 token implementation"
        license:
          type: string
          description: License of the contract
          example: "MIT"
          default: "UNLICENSED"
        created:
          type: string
          description: Creation timestamp
          example: "2023-01-15T10:30:00Z"
        verified:
          type: boolean
          description: Whether the contract is verified
          example: true
        tags:
          type: array
          items:
            type: string
          description: Tags associated with the contract
          example: ["token", "finance"]
        externalUrl:
          type: string
          nullable: true
          description: External URL for the contract
          example: "https://etherscan.io/address/0x123abc"
        address:
          type: string
          nullable: true
          description: Contract address
          example: "0x1234567890abcdef1234567890abcdef12345678"
        storage_protocol:
          type: string
          nullable: true
          description: Storage protocol used
          example: "IPFS"
        storage_address:
          type: string
          nullable: true
          description: Storage address
          example: "QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG"
        experimental:
          type: boolean
          nullable: true
          description: Whether the contract is experimental
          example: false
        solc_version:
          type: string
          nullable: true
          description: Solidity compiler version
          example: "0.8.19"
        verified_source:
          type: boolean
          nullable: true
          description: Whether the source code is verified
          example: true
        verified_source_code:
          type: string
          nullable: true
          description: Verified source code
        functionality:
          type: string
          nullable: true
          description: Contract functionality description
          example: "Token minting and burning with access controls"
        domain:
          type: string
          nullable: true
          description: Application domain
          example: "finance"
        security_risks_description:
          type: array
          items:
            type: string
          nullable: true
          description: Identified security risks description
          example: "This contract has a reentrancy vulnerability"
        similarity_score:
          type: number
          nullable: true
          description: Similarity score for vector search results
          example: 0.85

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Error message describing what went wrong
          example: "Internal server error occurred while processing the request"

tags:
  - name: contracts
    description: Smart contract search operations
